# retrieval/hierarchy/hierarchical_index.py
#
# Builds embeddings at 5 levels:
#
#   Level 1 — File    : one embedding per source file (full content summary)
#   Level 2 — Class   : one embedding per class / interface / enum
#   Level 3 — Method  : one embedding per method / function
#   Level 4 — Chunk   : one embedding per sliding-window chunk (same as flat)
#
# The hierarchical index is built on top of the flat chunk list that
# RepoChunker already produces — no re-scanning needed.
#
# Chunks are classified by their `type` field:
#   ClassDef / InterfaceDef   → level 2
#   MethodDef / FunctionDef   → level 3
#   everything else            → level 4
#
# File-level embeddings are generated by aggregating the docstrings and
# names of all chunks in the same file (cheap, no extra IO).
#

import time
import numpy as np
from collections import defaultdict
from typing import List, Dict, Any

from retrieval.hierarchy.hierarchical_store import HierarchicalStore
from retrieval.embedding_engine import EmbeddingEngine
from retrieval.index_tracker import IndexTracker

# Chunk type → level mapping
_TYPE_TO_LEVEL = {
    "ClassDef":     2,
    "InterfaceDef": 2,
    "EnumDef":      2,
    "MethodDef":    3,
    "FunctionDef":  3,
    "ConstructorDef": 3,
}
_DEFAULT_CHUNK_LEVEL = 4


class HierarchicalIndex:
    """
    Builds and queries the 5-level hierarchical vector store.

    Usage:
        idx = HierarchicalIndex(embedding_engine)
        idx.build(chunks)          # chunks from RepoChunker
        idx.save()
        # or:
        idx.load()                 # from cache
    """

    def __init__(self, embedding_engine: EmbeddingEngine = None):
        self.embedding_engine = embedding_engine or EmbeddingEngine()
        self.store: HierarchicalStore = None   # set after build() / load()
        self.tracker = IndexTracker()

    # =========================================================
    # BUILD
    # =========================================================

    def build(self, chunks: List[Dict[str, Any]]) -> None:
        """
        Classify chunks into levels, build file-level summaries,
        embed everything, and populate HierarchicalStore.
        """
        start = time.time()
        print("[HierarchicalIndex] Building hierarchical embeddings…")

        # --- Step 1: Group chunks by file ---
        by_file: Dict[str, List[Dict]] = defaultdict(list)
        for chunk in chunks:
            by_file[chunk.get("file", "__unknown__")].append(chunk)

        all_texts: List[str] = []
        all_levels: List[int] = []
        all_chunks: List[Dict] = []

        # --- Step 2: File-level synthetic chunks ---
        for file_path, file_chunks in by_file.items():
            file_chunk = self._make_file_chunk(file_path, file_chunks)
            all_texts.append(self._build_search_text(file_chunk))
            all_levels.append(1)
            all_chunks.append(file_chunk)

        # --- Step 3: Class / method / generic chunks ---
        for chunk in chunks:
            chunk_type = chunk.get("type", "")
            level = _TYPE_TO_LEVEL.get(chunk_type, _DEFAULT_CHUNK_LEVEL)
            all_texts.append(self._build_search_text(chunk))
            all_levels.append(level)
            all_chunks.append(chunk)

        # --- Step 4: Embed all at once ---
        print(f"[HierarchicalIndex] Embedding {len(all_texts)} items…")
        embeddings = self.embedding_engine.embed_batch(all_texts)

        dimension = embeddings.shape[1]
        self.store = HierarchicalStore(dimension)

        for embedding, level, chunk in zip(embeddings, all_levels, all_chunks):
            self.store.add(level, embedding, chunk)

        elapsed = time.time() - start
        print(
            f"[HierarchicalIndex] Built in {elapsed:.2f}s — "
            + str(self.store.sizes())
        )

    # =========================================================
    # SAVE / LOAD
    # =========================================================

    def save(self) -> None:
        if self.store:
            self.store.save()

    def load(self) -> bool:
        """Restore from cache. Returns True on success."""
        # Peek at dimension from existing flat index
        import faiss, os
        flat_path = ".cache/code_index.faiss"
        if not os.path.exists(flat_path):
            return False
        try:
            idx = faiss.read_index(flat_path)
            dimension = idx.d
        except Exception:
            return False

        self.store = HierarchicalStore(dimension)
        loaded = self.store.load()
        if loaded:
            print(f"[HierarchicalIndex] Loaded from cache — {self.store.sizes()}")
        return loaded

    def cache_exists(self) -> bool:
        if self.store:
            return self.store.cache_exists()
        import os
        return os.path.exists(".cache/hier_level_0.faiss")

    # =========================================================
    # HELPERS
    # =========================================================

    def _make_file_chunk(
        self, file_path: str, file_chunks: List[Dict]
    ) -> Dict[str, Any]:
        """Create a synthetic file-level chunk by aggregating sub-chunk metadata."""
        names = [c.get("name", "") for c in file_chunks if c.get("name")]
        docstrings = [c.get("docstring", "") for c in file_chunks if c.get("docstring")]
        imports = []
        for c in file_chunks:
            imports.extend(c.get("imports", []))
        imports = list(dict.fromkeys(imports))

        return {
            "chunk_id": f"{file_path}:__file__",
            "name": file_path,
            "type": "FileSummary",
            "parent": None,
            "file": file_path,
            "start_line": 1,
            "end_line": file_chunks[-1].get("end_line", 0) if file_chunks else 0,
            "imports": imports[:30],
            "docstring": " | ".join(docstrings[:3]),
            "code": " ".join(names[:50]),  # symbol names as pseudo-code
            "chunk_index": 0,
            "total_chunks": 1,
            "level": 1,
            "level_name": "file",
        }

    def _build_search_text(self, chunk: Dict) -> str:
        return (
            f"SYMBOL:\n{chunk.get('name', '')}\n\n"
            f"TYPE:\n{chunk.get('type', '')}\n\n"
            f"FILE:\n{chunk.get('file', '')}\n\n"
            f"LEVEL:\n{chunk.get('level_name', '')}\n\n"
            f"DOCSTRING:\n{chunk.get('docstring', '')}\n\n"
            f"IMPORTS:\n{' '.join(chunk.get('imports', []))}\n\n"
            f"CODE:\n{chunk.get('code', '')}\n"
        )
